# stages:
#   - install_deps
#   - test
#   - dev
#   - build

# default:
#   image: node:lts
#   pages:
#   before_script:
#     - yarn install

# Install Dependencies:
#   stage: install_deps
#   script:
#     - yarn install
#   when: manual

# Test:
#   stage: test
#   script:
#     - yarn test

# Dev:
#   stage: dev
#   script:
#     - yarn dev

# Build:
#   stage: build
#   script:
#     - yarn build
#   artifacts:
#     paths:
#       - public

image: node:lts
pages:
    stage: deploy
    script:
        - yarn install
        - yarn build
        - mv dist/ public/
    artifacts:
        paths:
            - public
    only:
        - main
